description: >
  Minimal docker image executor with marathon-cloud cli installed
docker:
  - image: 'marathonlabs/marathon-cloud:<<parameters.tag>>'
parameters:
  tag:
    default: 0.3.0
    description: >
      Pick a specific marathonlabs/marathon-cloud image variant:
      https://hub.docker.com/r/marathonlabs/marathon-cloud/tags
    type: string
